export const ADMIN_DASHBOARD_REQUEST = 'ADMIN_DASHBOARD_REQUEST';
export const ADMIN_DASHBOARD_SUCCESS = 'ADMIN_DASHBOARD_SUCCESS';
export const ADMIN_DASHBOARD_FAIL = 'ADMIN_DASHBOARD_FAIL';

export const DONOR_LIST_REQUEST = 'DONOR_LIST_REQUEST';
export const DONOR_LIST_SUCCESS = 'DONOR_LIST_SUCCESS';
export const DONOR_LIST_FAIL = 'DONOR_LIST_FAIL';

export const DONOR_UPDATE_REQUEST = 'DONOR_UPDATE_REQUEST';
export const DONOR_UPDATE_SUCCESS = 'DONOR_UPDATE_SUCCESS';
export const DONOR_UPDATE_FAIL = 'DONOR_UPDATE_FAIL';
export const DONOR_UPDATE_RESET = 'DONOR_UPDATE_RESET';

export const DONOR_DELETE_REQUEST = 'DONOR_DELETE_REQUEST';
export const DONOR_DELETE_SUCCESS = 'DONOR_DELETE_SUCCESS';
export const DONOR_DELETE_FAIL = 'DONOR_DELETE_FAIL';

export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST';
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS';
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL';

export const PATIENT_UPDATE_REQUEST = 'PATIENT_UPDATE_REQUEST';
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS';
export const PATIENT_UPDATE_FAIL = 'PATIENT_UPDATE_FAIL';
export const PATIENT_UPDATE_RESET = 'PATIENT_UPDATE_RESET';

export const PATIENT_DELETE_REQUEST = 'PATIENT_DELETE_REQUEST';
export const PATIENT_DELETE_SUCCESS = 'PATIENT_DELETE_SUCCESS';
export const PATIENT_DELETE_FAIL = 'PATIENT_DELETE_FAIL';

export const DONATION_REQUEST_LIST_REQUEST = 'DONATION_REQUEST_LIST_REQUEST';
export const DONATION_REQUEST_LIST_SUCCESS = 'DONATION_REQUEST_LIST_SUCCESS';
export const DONATION_REQUEST_LIST_FAIL = 'DONATION_REQUEST_LIST_FAIL';

export const DONATION_REQUEST_UPDATE_REQUEST = 'DONATION_REQUEST_UPDATE_REQUEST';
export const DONATION_REQUEST_UPDATE_SUCCESS = 'DONATION_REQUEST_UPDATE_SUCCESS';
export const DONATION_REQUEST_UPDATE_FAIL = 'DONATION_REQUEST_UPDATE_FAIL';
export const DONATION_REQUEST_UPDATE_RESET = 'DONATION_REQUEST_UPDATE_RESET';

export const BLOOD_REQUEST_LIST_REQUEST = 'BLOOD_REQUEST_LIST_REQUEST';
export const BLOOD_REQUEST_LIST_SUCCESS = 'BLOOD_REQUEST_LIST_SUCCESS';
export const BLOOD_REQUEST_LIST_FAIL = 'BLOOD_REQUEST_LIST_FAIL';

export const BLOOD_REQUEST_UPDATE_REQUEST = 'BLOOD_REQUEST_UPDATE_REQUEST';
export const BLOOD_REQUEST_UPDATE_SUCCESS = 'BLOOD_REQUEST_UPDATE_SUCCESS';
export const BLOOD_REQUEST_UPDATE_FAIL = 'BLOOD_REQUEST_UPDATE_FAIL';
export const BLOOD_REQUEST_UPDATE_RESET = 'BLOOD_REQUEST_UPDATE_RESET';

export const BLOOD_STOCK_UPDATE_REQUEST = 'BLOOD_STOCK_UPDATE_REQUEST';
export const BLOOD_STOCK_UPDATE_SUCCESS = 'BLOOD_STOCK_UPDATE_SUCCESS';
export const BLOOD_STOCK_UPDATE_FAIL = 'BLOOD_STOCK_UPDATE_FAIL';
export const BLOOD_STOCK_UPDATE_RESET = 'BLOOD_STOCK_UPDATE_RESET';
