// constants/bloodConstants.js
export const BLOOD_STOCK_REQUEST = 'BLOOD_STOCK_REQUEST';
export const BLOOD_STOCK_SUCCESS = 'BLOOD_STOCK_SUCCESS';
export const BLOOD_STOCK_FAIL = 'BLOOD_STOCK_FAIL';

export const BLOOD_STOCK_UPDATE_REQUEST = 'BLOOD_STOCK_UPDATE_REQUEST';
export const BLOOD_STOCK_UPDATE_SUCCESS = 'BLOOD_STOCK_UPDATE_SUCCESS';
export const BLOOD_STOCK_UPDATE_FAIL = 'BLOOD_STOCK_UPDATE_FAIL';
export const BLOOD_STOCK_UPDATE_RESET = 'BLOOD_STOCK_UPDATE_RESET';
