export const DONOR_DASHBOARD_REQUEST = 'DONOR_DASHBOARD_REQUEST';
export const DONOR_DASHBOARD_SUCCESS = 'DONOR_DASHBOARD_SUCCESS';
export const DONOR_DASHBOARD_FAIL = 'DONOR_DASHBOARD_FAIL';

export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST';
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS';
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL';
export const DONATION_CREATE_RESET = 'DONATION_CREATE_RESET';

export const DONATION_HISTORY_REQUEST = 'DONATION_HISTORY_REQUEST';
export const DONATION_HISTORY_SUCCESS = 'DONATION_HISTORY_SUCCESS';
export const DONATION_HISTORY_FAIL = 'DONATION_HISTORY_FAIL';

export const DONOR_BLOOD_REQUEST_CREATE_REQUEST = 'DONOR_BLOOD_REQUEST_CREATE_REQUEST';
export const DONOR_BLOOD_REQUEST_CREATE_SUCCESS = 'DONOR_BLOOD_REQUEST_CREATE_SUCCESS';
export const DONOR_BLOOD_REQUEST_CREATE_FAIL = 'DONOR_BLOOD_REQUEST_CREATE_FAIL';
export const DONOR_BLOOD_REQUEST_CREATE_RESET = 'DONOR_BLOOD_REQUEST_CREATE_RESET';

export const DONOR_BLOOD_REQUEST_HISTORY_REQUEST = 'DONOR_BLOOD_REQUEST_HISTORY_REQUEST';
export const DONOR_BLOOD_REQUEST_HISTORY_SUCCESS = 'DONOR_BLOOD_REQUEST_HISTORY_SUCCESS';
export const DONOR_BLOOD_REQUEST_HISTORY_FAIL = 'DONOR_BLOOD_REQUEST_HISTORY_FAIL';
