export const PATIENT_DASHBOARD_REQUEST = 'PATIENT_DASHBOARD_REQUEST';
export const PATIENT_DASHBOARD_SUCCESS = 'PATIENT_DASHBOARD_SUCCESS';
export const PATIENT_DASHBOARD_FAIL = 'PATIENT_DASHBOARD_FAIL';

export const PATIENT_BLOOD_REQUEST_CREATE_REQUEST = 'PATIENT_BLOOD_REQUEST_CREATE_REQUEST';
export const PATIENT_BLOOD_REQUEST_CREATE_SUCCESS = 'PATIENT_BLOOD_REQUEST_CREATE_SUCCESS';
export const PATIENT_BLOOD_REQUEST_CREATE_FAIL = 'PATIENT_BLOOD_REQUEST_CREATE_FAIL';
export const PATIENT_BLOOD_REQUEST_CREATE_RESET = 'PATIENT_BLOOD_REQUEST_CREATE_RESET';

export const PATIENT_BLOOD_REQUEST_HISTORY_REQUEST = 'PATIENT_BLOOD_REQUEST_HISTORY_REQUEST';
export const PATIENT_BLOOD_REQUEST_HISTORY_SUCCESS = 'PATIENT_BLOOD_REQUEST_HISTORY_SUCCESS';
export const PATIENT_BLOOD_REQUEST_HISTORY_FAIL = 'PATIENT_BLOOD_REQUEST_HISTORY_FAIL';
